/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
}
export type AttendanceStatus = { 'weekend' : null } |
  { 'present' : null } |
  { 'absent' : null } |
  { 'excused' : null } |
  { 'holiday' : null };
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'studentId' : string,
  'actorName' : string,
  'studentName' : string,
  'timestamp' : bigint,
}
export interface ContactNote {
  'id' : string,
  'studentId' : string,
  'createdAt' : bigint,
  'text' : string,
  'author' : string,
}
export interface LetterRecord {
  'id' : string,
  'studentId' : string,
  'sentAt' : bigint,
  'sentBy' : string,
}
export interface Student {
  'id' : string,
  'name' : string,
  'teacher' : string,
  'grade' : bigint,
}
export interface _SERVICE {
  'addNote' : ActorMethod<[string, string, string, string], string>,
  'clearAllData' : ActorMethod<[], undefined>,
  'dismissAlert' : ActorMethod<[string, string, string], undefined>,
  'getAllLetterHistory' : ActorMethod<[], Array<LetterRecord>>,
  'getAllNotes' : ActorMethod<[], Array<ContactNote>>,
  'getAttendanceForDateRange' : ActorMethod<
    [string, string],
    Array<AttendanceRecord>
  >,
  'getAttendanceForStudent' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAuditLog' : ActorMethod<[], Array<AuditEntry>>,
  'getDismissedAlerts' : ActorMethod<[], Array<string>>,
  'getLetterHistoryForStudent' : ActorMethod<[string], Array<LetterRecord>>,
  'getNotesForStudent' : ActorMethod<[string], Array<ContactNote>>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getStudentsByGrade' : ActorMethod<[bigint], Array<Student>>,
  'getStudentsByTeacher' : ActorMethod<[string], Array<Student>>,
  'reinstateAlert' : ActorMethod<[string], undefined>,
  'sendLetter' : ActorMethod<[string, string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];