/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LetterRecord = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'sentAt' : IDL.Int,
  'sentBy' : IDL.Text,
});
export const ContactNote = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'weekend' : IDL.Null,
  'present' : IDL.Null,
  'absent' : IDL.Null,
  'excused' : IDL.Null,
  'holiday' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'studentId' : IDL.Text,
  'actorName' : IDL.Text,
  'studentName' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'teacher' : IDL.Text,
  'grade' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'clearAllData' : IDL.Func([], [], []),
  'dismissAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllLetterHistory' : IDL.Func([], [IDL.Vec(LetterRecord)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(ContactNote)], ['query']),
  'getAttendanceForDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceForStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'getDismissedAlerts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLetterHistoryForStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LetterRecord)],
      ['query'],
    ),
  'getNotesForStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactNote)],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentsByGrade' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getStudentsByTeacher' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'reinstateAlert' : IDL.Func([IDL.Text], [], []),
  'sendLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LetterRecord = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'sentAt' : IDL.Int,
    'sentBy' : IDL.Text,
  });
  const ContactNote = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'weekend' : IDL.Null,
    'present' : IDL.Null,
    'absent' : IDL.Null,
    'excused' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'studentId' : IDL.Text,
    'actorName' : IDL.Text,
    'studentName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'teacher' : IDL.Text,
    'grade' : IDL.Nat,
  });
  
  return IDL.Service({
    'addNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'clearAllData' : IDL.Func([], [], []),
    'dismissAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllLetterHistory' : IDL.Func([], [IDL.Vec(LetterRecord)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(ContactNote)], ['query']),
    'getAttendanceForDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceForStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'getDismissedAlerts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLetterHistoryForStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LetterRecord)],
        ['query'],
      ),
    'getNotesForStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactNote)],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudentsByGrade' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getStudentsByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'reinstateAlert' : IDL.Func([IDL.Text], [], []),
    'sendLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };